
import random
from PyQt6 import QtCore, QtGui, QtWidgets
ls = ['1.png','2.png','3.png','4.png','5.png','6.png','7.png','8.png','9.png']
score = 0
ls1 = []
def choising():
     r = random.choice(ls)
     if r not in ls1:
          ls1.append(r)
          return r
     else:
          choising()  
for i in range(9):
        choising()                  
print(ls1)
hidden = ls1[random.randint(1,9)]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 600)
        MainWindow.setMinimumSize(QtCore.QSize(840, 600))
        MainWindow.setMaximumSize(QtCore.QSize(840, 600))
        MainWindow.setStyleSheet("background-color: #EEE3CB;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picture_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_1.setGeometry(QtCore.QRect(120, 140, 100, 100))
        self.picture_1.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_1.setIcon(icon)
        self.picture_1.setIconSize(QtCore.QSize(60, 60))
        self.picture_1.setObjectName("picture_1")
        self.picture_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_8.setGeometry(QtCore.QRect(260, 390, 100, 100))
        self.picture_8.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/8.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_8.setIcon(icon1)
        self.picture_8.setIconSize(QtCore.QSize(50, 50))
        self.picture_8.setObjectName("picture_8")
        self.picture_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_3.setGeometry(QtCore.QRect(400, 140, 100, 100))
        self.picture_3.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_3.setIcon(icon2)
        self.picture_3.setIconSize(QtCore.QSize(60, 60))
        self.picture_3.setObjectName("picture_3")
        self.picture_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_2.setGeometry(QtCore.QRect(260, 140, 100, 100))
        self.picture_2.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_2.setIcon(icon3)
        self.picture_2.setIconSize(QtCore.QSize(50, 50))
        self.picture_2.setObjectName("picture_2")
        self.picture_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_7.setGeometry(QtCore.QRect(120, 390, 100, 100))
        self.picture_7.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/7.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_7.setIcon(icon4)
        self.picture_7.setIconSize(QtCore.QSize(60, 60))
        self.picture_7.setObjectName("picture_7")
        self.picture_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_6.setGeometry(QtCore.QRect(400, 270, 100, 100))
        self.picture_6.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/6.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_6.setIcon(icon5)
        self.picture_6.setIconSize(QtCore.QSize(50, 50))
        self.picture_6.setObjectName("picture_6")
        self.picture_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_5.setGeometry(QtCore.QRect(260, 270, 100, 100))
        self.picture_5.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/5.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_5.setIcon(icon6)
        self.picture_5.setIconSize(QtCore.QSize(60, 60))
        self.picture_5.setObjectName("picture_5")
        self.picture_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_4.setGeometry(QtCore.QRect(120, 270, 100, 100))
        self.picture_4.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/6.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_4.setIcon(icon7)
        self.picture_4.setIconSize(QtCore.QSize(50, 50))
        self.picture_4.setObjectName("picture_4")
        self.hide_and_show_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hide_and_show_button.setGeometry(QtCore.QRect(630, 140, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.hide_and_show_button.setFont(font)
        self.hide_and_show_button.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.hide_and_show_button.setObjectName("hide_and_show_button")
        self.picture_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.picture_9.setGeometry(QtCore.QRect(400, 390, 100, 100))
        self.picture_9.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.picture_9.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/9.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.picture_9.setIcon(icon8)
        self.picture_9.setIconSize(QtCore.QSize(50, 50))
        self.picture_9.setObjectName("picture_9")
        self.refresh_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(770, 10, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.refresh_button.setFont(font)
        self.refresh_button.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.refresh_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.refresh_button.setIcon(icon9)
        self.refresh_button.setIconSize(QtCore.QSize(30, 30))
        self.refresh_button.setObjectName("refresh_button")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.to_find = QtWidgets.QPushButton(parent=self.centralwidget)
        self.to_find.setGeometry(QtCore.QRect(630, 270, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.to_find.setFont(font)
        self.to_find.setStyleSheet("border: 1px solid #967E76;\n"
"background-color: #B7C4CF;")
        self.to_find.setText("")
        self.to_find.setIcon(icon8)
        self.to_find.setIconSize(QtCore.QSize(60, 60))
        self.to_find.setObjectName("to_find")
        self.score = QtWidgets.QLabel(parent=self.centralwidget)
        self.score.setGeometry(QtCore.QRect(50, 520, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setStyleSheet("font-size: 16px;\n"
"font-weight: 600;")
        self.score.setWordWrap(False)
        self.score.setObjectName("score")
        self.score_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_num.setGeometry(QtCore.QRect(100, 520, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.score_num.setFont(font)
        self.score_num.setStyleSheet("font-size: 16px;\n"
"font-weight: 600;")
        self.score_num.setWordWrap(False)
        self.score_num.setObjectName("score_num")
        self.attamp = QtWidgets.QLabel(parent=self.centralwidget)
        self.attamp.setGeometry(QtCore.QRect(630, 520, 70, 20))
        self.attamp.setStyleSheet("font-size: 16px;Font-weight: 500;")
        self.attamp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.attamp.setWordWrap(False)
        self.attamp.setObjectName("attamp")
        self.attamp_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.attamp_num.setGeometry(QtCore.QRect(705, 520, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.attamp_num.setFont(font)
        self.attamp_num.setStyleSheet("font-size: 16px;Font-weight: 500;")
        self.attamp_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.attamp_num.setWordWrap(False)
        self.attamp_num.setObjectName("attamp_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.hide_and_show_button.clicked.connect(self.hide_pictures)
        self.refresh_button.clicked.connect(self.refresh_sites)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        if ls1[0] == hidden:             
                self.picture_1.clicked.connect(self.open_card_1)
                score += 1
                self.score_num.setText(score)
        self.picture_2.clicked.connect(self.open_card_2)
        self.picture_3.clicked.connect(self.open_card_3)
        self.picture_4.clicked.connect(self.open_card_4)
        self.picture_5.clicked.connect(self.open_card_5)
        self.picture_6.clicked.connect(self.open_card_6)
        self.picture_7.clicked.connect(self.open_card_7)
        self.picture_8.clicked.connect(self.open_card_8)
        self.picture_9.clicked.connect(self.open_card_9)
    def open_card_1(self):         
        self.picture_1.setIcon(QtGui.QIcon(f"img/{ls1[0]}"))
    def open_card_2(self):         
        self.picture_2.setIcon(QtGui.QIcon(f"img/{ls1[1]}"))
    def open_card_3(self):         
        self.picture_3.setIcon(QtGui.QIcon(f"img/{ls1[2]}"))
    def open_card_4(self):         
        self.picture_4.setIcon(QtGui.QIcon(f"img/{ls1[3]}"))
    def open_card_5(self):         
        self.picture_5.setIcon(QtGui.QIcon(f"img/{ls1[4]}"))  
    def open_card_6(self):         
        self.picture_6.setIcon(QtGui.QIcon(f"img/{ls1[5]}"))                  
    def open_card_7(self):         
        self.picture_7.setIcon(QtGui.QIcon(f"img/{ls1[6]}"))    
    def open_card_8(self):         
        self.picture_8.setIcon(QtGui.QIcon(f"img/{ls1[7]}"))    
    def open_card_9(self):         
        self.picture_9.setIcon(QtGui.QIcon(f"img/{ls1[8]}")) 

    def refresh_sites(self):        
        random.shuffle(ls1) 
        self.picture_1.setIcon(QtGui.QIcon(f"img/{ls1[0]}"))
        self.picture_2.setIcon(QtGui.QIcon(f"img/{ls1[1]}"))
        self.picture_3.setIcon(QtGui.QIcon(f"img/{ls1[2]}"))
        self.picture_4.setIcon(QtGui.QIcon(f"img/{ls1[3]}"))
        self.picture_5.setIcon(QtGui.QIcon(f"img/{ls1[4]}"))
        self.picture_6.setIcon(QtGui.QIcon(f"img/{ls1[5]}"))
        self.picture_7.setIcon(QtGui.QIcon(f"img/{ls1[6]}"))
        self.picture_8.setIcon(QtGui.QIcon(f"img/{ls1[7]}"))
        self.picture_9.setIcon(QtGui.QIcon(f"img/{ls1[8]}"))
        self.to_find.setIcon(QtGui.QIcon(f"img/{hidden}"))

    def hide_pictures(self):
        if (self.hide_and_show_button.text() == 'Hide'):
                
                self.picture_1.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_2.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_3.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_4.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_5.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_6.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_7.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_8.setIcon(QtGui.QIcon('img/ramadan .png'))
                self.picture_9.setIcon(QtGui.QIcon('img/ramadan .png'))
                
                self.hide_and_show_button.setText('Show')
                self.refresh_button.setDisabled(True)
        else:
                random.shuffle(ls1)
                self.to_find.setIcon(QtGui.QIcon(f"img/{hidden}"))
                self.hide_and_show_button.setText("Hide")                     
                self.picture_1.setIcon(QtGui.QIcon(f"img/{ls1[0]}"))
                self.picture_2.setIcon(QtGui.QIcon(f"img/{ls1[1]}"))
                self.picture_3.setIcon(QtGui.QIcon(f"img/{ls1[2]}"))
                self.picture_4.setIcon(QtGui.QIcon(f"img/{ls1[3]}"))
                self.picture_5.setIcon(QtGui.QIcon(f"img/{ls1[4]}"))
                self.picture_6.setIcon(QtGui.QIcon(f"img/{ls1[5]}"))
                self.picture_7.setIcon(QtGui.QIcon(f"img/{ls1[6]}"))
                self.picture_8.setIcon(QtGui.QIcon(f"img/{ls1[7]}"))
                self.picture_9.setIcon(QtGui.QIcon(f"img/{ls1[8]}"))
                self.refresh_button.setDisabled(False)
            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hide_and_show_button.setText(_translate("MainWindow", "Hide"))
        self.label.setText(_translate("MainWindow", "Game for Ramadan"))
        self.score.setText(_translate("MainWindow", "Score:"))
        self.score_num.setText(_translate("MainWindow", f"{score}"))
        self.attamp.setText(_translate("MainWindow", "Attamps:"))
        self.attamp_num.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
